110 - Ported search to use typeorm
ubclaunchpad/Internado pull request #117
Opened 2018-11-20 03:46 UTC by cowmanjoe

The search API now uses typeorm as an ORM for querying and representing the data as typed objects. This also includes the changes I made for #99 and #94 (added filtering parameters).

2018-11-20 06:17 UTC, cowmanjoe commented
Also, the database I have with all the sample data can be generated by using the command `psql db_name < internado.out` where db_name is the name of your database on your local instance and internado.out is the path to this [pg_dump file](https://mega.nz/#!09s2BKpY!aZnN6NMnikhmuSq33vTo_nPaLq37t3rJ8pQs03MqoOk).

2018-11-21 04:22 UTC, frostyshadows requested changes
haven't tested it thoroughly yet, but looks good so far! left a few comments

2018-11-21 04:22 UTC, frostyshadows commented on server/models/job.ts
> +    public city: string;
I just added a "state" column to the proposed schema, since a country could have a few cities with the same name. Could you add it as part of this PR? https://github.com/ubclaunchpad/Internado/wiki/Proposed-Database-Schema

2018-11-21 04:22 UTC, frostyshadows commented on server/controllers/searchController.ts
> +import {Connection, createConnection, getConnection, SelectQueryBuilder} from "typeorm";
createConnection isn't actually used, so it doesn't have to be imported

2018-11-21 04:22 UTC, frostyshadows commented on server/controllers/searchController.ts
> +        res.status(400).send("If radius is defined radius, longitude and latitude must be valid.");
I think this should be `If radius is defined radius, longitude and latitude must be valid.`

2018-11-21 22:01 UTC, cowmanjoe commented
I've updated the schema in my code to match the [proposed schema](https://github.com/ubclaunchpad/Internado/wiki/Proposed-Database-Schema) in the wiki. Also updated the [pg_dump file](https://mega.nz/#!1hlwVaKQ!17pMbyhXCCb3EiojIqhP6UQdT9N_M0kFz-3fDEd7fxU) so it matches that schema. To use this file on your local machine, install postgres and create a database. Once that database is running run `psql {db_name} < internado.sql` in the directory where the internado.sql file I've linked is located.

2018-11-22 00:40 UTC, kimoantiqe commented
@cowmanjoe Shall I update my PR ( #118) with the above new pg dump ?

2018-11-22 01:00 UTC, cowmanjoe commented
@kimoantiqe Yup, sounds good.

2018-11-22 19:48 UTC, frostyshadows approved these changes

2018-11-22 23:06 UTC, merged