Feature/116
ubclaunchpad/Internado pull request #141
Opened 2018-12-26 22:40 UTC by frostyshadows

With this PR, the `location` and `salary` filters are being used to build the search query. The other 2 filters are `categories` and `industries`, but they don't really map to anything in the searchRequest interface and may still change depending on new designs.

Notes
- Right now if the user doesn't put in an actual number in the salary field, the salaryMin just gets left out of the search request.
- All the latlngs in our database are 0.0, 0.0 since ZipRecruiter's data doesn't contain latlng. So if you actually input a location you won't get any results, but you can check the network log in the chrome developer tools to make sure the search request payload contains latitude, longitude and radius.

2018-12-27 22:25 UTC, cowmanjoe requested changes
Solid stuff. Couple things I think should change: 
* Using onSelect instead of onChange for querying lat lon
* Finding a way to clear the location filter when the address is empty (probably some handling in onChange to check if the string is empty)

2018-12-27 22:25 UTC, cowmanjoe commented on client/src/App.js
> +// import ResultsTable from './components/ResultsTable';
We can probably remove these if they're unused.

2018-12-27 22:25 UTC, cowmanjoe commented on client/src/App.js
> +        {/* <ResultsTable results={this.state.data} /> */}
This can probably be removed as well.

2018-12-27 22:25 UTC, cowmanjoe commented on client/src/components/FilterMenu.js
>    }
Instead of this logic happening every time the location changes, I think it should only happen on select. With this implementation, it is quite slow typing a location since it queries for lat lon every key stroke. If it is done on select, it performs well. This way we can only query data if it is selected from the drop down, which may or may not be a drawback. 

```
  handleLocationChange = address => {
    this.setState({address});
  }

  handleSelect = address => {
    geocodeByAddress(address)
      .then(results => getLatLng(results[0]))
      .then(latLng => {
        console.log('Success', latLng);
        this.setState({address});
        this.props.changeLocation(latLng);
      })
      .catch(error => console.error('Error', error));

  }
```

2018-12-27 22:25 UTC, cowmanjoe commented on client/src/components/FilterMenu.js
> +              onChange={this.handleLocationChange}>
Add here `onSelect={this.handleSelect}` (if you are going with my onSelect change). Maybe use `this.handleLocationSelect` to match the naming convention.

2018-12-28 04:40 UTC, frostyshadows commented on client/src/App.js
> +// import ResultsTable from './components/ResultsTable';
good point, deleted them

2018-12-28 23:04 UTC, cowmanjoe approved these changes

2018-12-28 23:05 UTC, cowmanjoe commented
Awesome, approved! I think we can merge this in.

2018-12-29 20:37 UTC, merged