update coding standard
ubclaunchpad/Internado pull request #155
Opened 2019-01-12 05:39 UTC by AmirNaghibi

- single quote
- 2  space tab

2019-01-12 22:06 UTC, DConnorFong requested changes

2019-01-12 22:06 UTC, DConnorFong commented on client/src/components/Dropdown.js
> -      <div className="dropdown">
I think HTML convention is to have double-quotations. Javascript is fine to change to single quotations.

2019-01-12 22:06 UTC, DConnorFong commented on client/src/components/FilterMenu.js
> +    <div className='autocomplete-root'>
@AmirNaghibi think HTML convention is to have double-quotations. Javascript is fine to change to single quotations.

2019-01-12 22:06 UTC, DConnorFong commented on client/src/components/FilterMenu.js
> +    <div className='autocomplete-root'>
@kimoantiqe

2019-01-15 09:44 UTC, cowmanjoe requested changes

2019-01-15 09:44 UTC, cowmanjoe commented on client/src/actions/postingsActions.js
> +      body: `{'keywords': '${searchKeywords}'}`,
This is a JSON literal, so I don't think it would be allowed to have single quotes.

2019-03-02 19:42 UTC, closed without merging