Feature/151
ubclaunchpad/Internado pull request #160
Opened 2019-01-12 21:46 UTC by MichaelXian

2019-01-12 22:06 UTC, DConnorFong requested changes

2019-01-12 22:06 UTC, DConnorFong commented on database_config/init.sql
> +ALTER TABLE public.job OWNER TO postgres;
Why is this changed to postgres?

2019-01-12 22:18 UTC, DConnorFong approved these changes
Nice

2019-01-12 22:31 UTC, merged

2019-01-15 08:28 UTC, cowmanjoe reviewed
I'll make a ticket for fixing this. Can this merge be reverted? It breaks the server.

2019-01-15 08:28 UTC, cowmanjoe commented on server/controllers/searchController.ts
> -        .addSelect(`setweight(to_tsvector(job.job_title), 'A') ||
Little late but these are query literals here, they need to be single quotes.

2019-01-15 08:28 UTC, cowmanjoe commented on server/controllers/searchController.ts
> -    qb.where("job_document @@ to_tsquery(:keywords)", {keywords: `'${search.keywords}'`});
Same here I believe.