Added a /swagger endpoint to access swagger UI.
ubclaunchpad/Internado pull request #166
Opened 2019-01-15 09:39 UTC by cowmanjoe

Swagger uses the OpenAPI spec to display API documentation in a clean and interactive way. The server now uses Swagger to do just this. Just access the /swagger endpoint in a browser to test it out! An instance of our Postgres database also needs to be running on your machine for this to work. 

The server/swagger.json file contains all the information that Swagger uses to display the API. If we keep using this, any new API endpoint should be documented in this file. OpenAPI is relatively simple to use, and there is plenty of documentation online for it.

2019-01-15 09:39 UTC, cowmanjoe commented on server/controllers/mailingListController.ts
> +        res.status(400).send({error: "Email address query parameter is required"});
This is unrelated to the PR but a bug I discovered as I was trying to get it working.

2019-01-19 22:03 UTC, frostyshadows requested changes
Could you also add info on how to access the Swagger page on the main README?

2019-01-19 22:03 UTC, frostyshadows commented on server/swagger.json
> +    "description": "This is the API for Internado's back end. It's main function right now is searching for other internships in the database. Check out our [git repo](https://github.com/ubclaunchpad
should be `Its main function` instead of `It's main function`

2019-01-23 23:23 UTC, frostyshadows approved these changes
LGTM 🌪

2019-01-25 00:38 UTC, merged